# Generated by Django 5.0.6 on 2024-07-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrd', '0002_remove_recipe_slug_recipe_excerpt_recipe_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='content',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='No ingredients specified'),
        ),
    ]
